# Generated by Django 4.1.5 on 2023-01-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userorder_order_userorder_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
