# Generated by Django 4.1.5 on 2023-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_available_alter_product_created_and_more'),
        ('cart', '0002_cartproduct_cartuser_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartuser',
            name='in_order',
        ),
        migrations.RemoveField(
            model_name='cartuser',
            name='total_products',
        ),
        migrations.AlterField(
            model_name='cartuser',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='shop.product'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
