# Generated by Django 4.1.5 on 2023-01-15 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_product_available_alter_product_created_and_more'),
        ('cart', '0004_alter_cartuser_final_price_remove_cartuser_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartuser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cartuser',
            name='products',
        ),
        migrations.AddField(
            model_name='cartuser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины'),
        ),
        migrations.AddField(
            model_name='cartuser',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_cart', to='shop.product'),
        ),
    ]
