# Generated by Django 4.1.5 on 2023-01-16 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_product_available_alter_product_created_and_more'),
        ('cart', '0007_cartuser_remove_productinbasket_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartuser',
            name='user',
            field=models.ManyToManyField(related_name='cartUser', to=settings.AUTH_USER_MODEL, verbose_name='Корзина пользователя'),
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('product', models.ManyToManyField(related_name='productCart', to='shop.product', verbose_name='Продукт корзины')),
            ],
        ),
        migrations.AddField(
            model_name='cartuser',
            name='pcart',
            field=models.ManyToManyField(to='cart.productcart'),
        ),
    ]
