# Generated by Django 4.1.5 on 2023-01-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_productcart_price_cartuser_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
