# Generated by Django 4.1.5 on 2023-01-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_available_alter_product_created_and_more'),
        ('cart', '0011_remove_cartuser_user_cartuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartuser',
            name='pcart',
            field=models.ManyToManyField(to='shop.product'),
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
