# Generated by Django 4.1.5 on 2023-01-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_available_alter_product_created_and_more'),
        ('cart', '0012_alter_cartuser_pcart_delete_productcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartuser',
            name='pcart',
        ),
        migrations.AddField(
            model_name='cartuser',
            name='pcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
