# Generated by Django 4.1.5 on 2023-01-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_available_alter_product_created_and_more'),
        ('cart', '0013_remove_cartuser_pcart_cartuser_pcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartuser',
            name='pcart',
        ),
        migrations.AddField(
            model_name='cartuser',
            name='pcart',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
