# Generated by Django 4.1.5 on 2023-01-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cartproduct_alter_cartuser_pcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartuser',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cartuser',
            name='pcart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.AddField(
            model_name='cartuser',
            name='pcart',
            field=models.JSONField(null=True),
        ),
    ]
